// Generated by https://quicktype.io

export interface IReply {
    kind: Kind;
    data: IReplyData;
}

export interface IReplyData {
    children?:                       string;
    total_awards_received:           number;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    ups:                             number;
    removal_reason:                  null;
    link_id:                         LinkID;
    author_flair_template_id:        null;
    likes:                           null;
    replies:                         DataRepliesClass;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           string;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    approved_by:                     null;
    report_reasons:                  null;
    all_awardings:                   AllAwarding[];
    subreddit_id:                    SubredditID;
    body:                            string;
    edited:                          boolean;
    author_flair_css_class:          null;
    collapsed:                       boolean;
    downs:                           number;
    is_submitter:                    boolean;
    body_html:                       string;
    gildings:                        Gildings;
    collapsed_reason:                null;
    associated_award:                null;
    stickied:                        boolean;
    subreddit_type:                  SubredditType;
    can_gild:                        boolean;
    top_awarded_type:                null;
    unrepliable_reason:              null;
    author_flair_text_color:         string;
    score_hidden:                    boolean;
    permalink:                       string;
    num_reports:                     null;
    locked:                          boolean;
    name:                            Name;
    created:                         number;
    subreddit:                       Subreddit;
    author_flair_text:               null;
    treatment_tags:                  string[];
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   string;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    mod_note:                        null;
    distinguished:                   null;
}

export interface AllAwarding {
    giver_coin_reward:                    null;
    subreddit_id:                         null;
    is_new:                               boolean;
    days_of_drip_extension:               null;
    coin_price:                           number;
    id:                                   string;
    penny_donate:                         null;
    coin_reward:                          number;
    icon_url:                             string;
    days_of_premium:                      null;
    icon_height:                          number;
    tiers_by_required_awardings:          null;
    resized_icons:                        ResizedIcon[];
    icon_width:                           number;
    static_icon_width:                    number;
    start_date:                           null;
    is_enabled:                           boolean;
    awardings_required_to_grant_benefits: null;
    description:                          string;
    end_date:                             null;
    sticky_duration_seconds:              null;
    subreddit_coin_reward:                number;
    count:                                number;
    static_icon_height:                   number;
    name:                                 string;
    resized_static_icons:                 ResizedIcon[];
    icon_format:                          string;
    award_sub_type:                       string;
    penny_price:                          number;
    award_type:                           string;
    static_icon_url:                      string;
}

export interface ResizedIcon {
    url:    string;
    width:  number;
    height: number;
}

export interface Gildings {
}

export enum LinkID {
    T311Al04Z = "t3_11al04z",
}

export enum Name {
    T1J9Ssmjf = "t1_j9ssmjf",
}

export interface DataRepliesClass {
    kind: string;
    data: PurpleData;
}

export interface PurpleData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   PurpleChild[];
    before:     null;
}

export interface PurpleChild {
    kind: Kind;
    data: FluffyData;
}

export interface FluffyData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type?:              AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    likes:                           null;
    replies:                         PurpleReplies | string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       Name;
    score:                           number;
    author_fullname?:                string;
    removal_reason:                  null;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    body:                            string;
    edited:                          boolean;
    top_awarded_type:                null;
    downs:                           number;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    collapsed:                       boolean;
    author_flair_richtext?:          any[];
    author_patreon_flair?:           boolean;
    body_html:                       string;
    gildings:                        Gildings;
    collapsed_reason:                null;
    distinguished:                   null;
    associated_award:                null;
    stickied:                        boolean;
    author_premium?:                 boolean;
    can_gild:                        boolean;
    link_id:                         LinkID;
    unrepliable_reason:              null;
    author_flair_text_color:         null | string;
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    treatment_tags:                  any[];
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null | string;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export enum AuthorFlairType {
    Text = "text",
}

export interface PurpleReplies {
    kind: string;
    data: TentacledData;
}

export interface TentacledData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   FluffyChild[];
    before:     null;
}

export interface FluffyChild {
    kind: Kind;
    data: StickyData;
}

export interface StickyData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type:               AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    likes:                           null;
    replies:                         FluffyReplies | string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    author_fullname:                 string;
    removal_reason:                  null;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    collapsed:                       boolean;
    body:                            string;
    edited:                          boolean;
    top_awarded_type:                null;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    downs:                           number;
    author_flair_richtext:           any[];
    author_patreon_flair:            boolean;
    body_html:                       string;
    gildings:                        Gildings;
    collapsed_reason:                null;
    distinguished:                   null;
    associated_award:                null;
    stickied:                        boolean;
    author_premium:                  boolean;
    can_gild:                        boolean;
    link_id:                         LinkID;
    unrepliable_reason:              null;
    author_flair_text_color:         null;
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    treatment_tags:                  any[];
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export interface FluffyReplies {
    kind: string;
    data: IndigoData;
}

export interface IndigoData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   TentacledChild[];
    before:     null;
}

export interface TentacledChild {
    kind: Kind;
    data: IndecentData;
}

export interface IndecentData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type:               AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    distinguished:                   null;
    likes:                           null;
    replies:                         TentacledReplies | string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    author_fullname:                 string;
    removal_reason:                  null;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    body:                            string;
    edited:                          boolean;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    downs:                           number;
    author_flair_richtext:           any[];
    author_patreon_flair:            boolean;
    body_html:                       string;
    gildings:                        Gildings;
    collapsed_reason:                null;
    link_id:                         LinkID;
    associated_award:                null;
    stickied:                        boolean;
    author_premium:                  boolean;
    can_gild:                        boolean;
    top_awarded_type:                null;
    unrepliable_reason:              null;
    author_flair_text_color:         null;
    treatment_tags:                  any[];
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    collapsed:                       boolean;
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export interface TentacledReplies {
    kind: string;
    data: HilariousData;
}

export interface HilariousData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   StickyChild[];
    before:     null;
}

export interface StickyChild {
    kind: Kind;
    data: AmbitiousData;
}

export interface AmbitiousData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type:               AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    distinguished:                   null;
    likes:                           null;
    replies:                         StickyReplies | string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    author_fullname:                 string;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    body:                            string;
    edited:                          boolean;
    gildings:                        Gildings;
    downs:                           number;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    collapsed:                       boolean;
    author_flair_richtext:           any[];
    author_patreon_flair:            boolean;
    body_html:                       string;
    removal_reason:                  null;
    collapsed_reason:                null;
    link_id:                         LinkID;
    associated_award:                null;
    stickied:                        boolean;
    author_premium:                  boolean;
    can_gild:                        boolean;
    top_awarded_type:                null;
    unrepliable_reason:              null;
    author_flair_text_color:         null;
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    treatment_tags:                  any[];
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export interface StickyReplies {
    kind: string;
    data: CunningData;
}

export interface CunningData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   IndigoChild[];
    before:     null;
}

export interface IndigoChild {
    kind: Kind;
    data: MagentaData;
}

export interface MagentaData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type:               AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    distinguished:                   null;
    likes:                           null;
    replies:                         IndigoReplies | string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    author_fullname:                 string;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    collapsed:                       boolean;
    body:                            string;
    edited:                          boolean;
    gildings:                        Gildings;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    downs:                           number;
    author_flair_richtext:           any[];
    author_patreon_flair:            boolean;
    body_html:                       string;
    removal_reason:                  null;
    collapsed_reason:                null;
    link_id:                         LinkID;
    associated_award:                null;
    stickied:                        boolean;
    author_premium:                  boolean;
    can_gild:                        boolean;
    top_awarded_type:                null;
    unrepliable_reason:              null;
    author_flair_text_color:         null;
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    treatment_tags:                  any[];
    created_utc:                     number;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export interface IndigoReplies {
    kind: string;
    data: FriskyData;
}

export interface FriskyData {
    after:      null;
    dist:       null;
    modhash:    string;
    geo_filter: string;
    children:   IndecentChild[];
    before:     null;
}

export interface IndecentChild {
    kind: Kind;
    data: MischievousData;
}

export interface MischievousData {
    subreddit_id:                    SubredditID;
    approved_at_utc:                 null;
    author_is_blocked:               boolean;
    comment_type:                    null;
    awarders:                        any[];
    mod_reason_by:                   null;
    banned_by:                       null;
    author_flair_type:               AuthorFlairType;
    total_awards_received:           number;
    subreddit:                       Subreddit;
    author_flair_template_id:        null;
    distinguished:                   null;
    likes:                           null;
    replies:                         string;
    user_reports:                    any[];
    saved:                           boolean;
    id:                              string;
    banned_at_utc:                   null;
    mod_reason_title:                null;
    gilded:                          number;
    archived:                        boolean;
    collapsed_reason_code:           null;
    no_follow:                       boolean;
    author:                          string;
    can_mod_post:                    boolean;
    created_utc:                     number;
    send_replies:                    boolean;
    parent_id:                       string;
    score:                           number;
    author_fullname:                 string;
    approved_by:                     null;
    mod_note:                        null;
    all_awardings:                   any[];
    body:                            string;
    edited:                          boolean;
    gildings:                        Gildings;
    author_flair_css_class:          null;
    name:                            string;
    is_submitter:                    boolean;
    downs:                           number;
    author_flair_richtext:           any[];
    author_patreon_flair:            boolean;
    body_html:                       string;
    removal_reason:                  null;
    collapsed_reason:                null;
    link_id:                         LinkID;
    associated_award:                null;
    stickied:                        boolean;
    author_premium:                  boolean;
    can_gild:                        boolean;
    top_awarded_type:                null;
    unrepliable_reason:              null;
    author_flair_text_color:         null;
    score_hidden:                    boolean;
    permalink:                       string;
    subreddit_type:                  SubredditType;
    locked:                          boolean;
    report_reasons:                  null;
    created:                         number;
    author_flair_text:               null;
    treatment_tags:                  any[];
    collapsed:                       boolean;
    subreddit_name_prefixed:         SubredditNamePrefixed;
    controversiality:                number;
    depth:                           number;
    author_flair_background_color:   null;
    collapsed_because_crowd_control: null;
    mod_reports:                     any[];
    num_reports:                     null;
    ups:                             number;
}

export enum Subreddit {
    ThatsInsane = "ThatsInsane",
}

export enum SubredditID {
    T5Swxxz = "t5_swxxz",
}

export enum SubredditNamePrefixed {
    RThatsInsane = "r/ThatsInsane",
}

export enum SubredditType {
    Public = "public",
}

export enum Kind {
    T1 = "t1",
    more = 'more'
}
